langage : node_js
node_js: 12

stages:
  - lint

jobs:
  includes:
  - name: Eslint
  stage: lint
  install: npm install
  script: npm start

  stages: 
    - trasnpile

  jobs:
    includes:
      - name: 