langage : node_js
node_js: 12

stages:
  - lint

jobs:
  includes:
  - name: Eslint
  stage: lint
  install: npm install
  script: npm run build

  stages: 
    - trasnpile

  jobs:
    includes:
      - name: Transpile
      stage: transpile
      install: npm install
      script: npm run build