langage : node_js
node_js: 12

stages:
  - Global Testing
  - ':rocket: Deployment'

jobs:
  include:
  - stage: Global Testing
    name: compile
    install: npm install
    script: npm build

  - stage: Global Testing
    name: tests
    install: npm install
    script: npm test



  - stage: global testing
    name: Eslint
    stage: lint
    install: npm install
    script: npm run build


  - stage: global testing
    name: Transpile
    stage: transpile
    install: npm install
    script: npm run build